import {
  ApplicationSource,
  ApplicationStatus,
  ExperienceLevel,
  JobNature,
  Priority,
  WorkMode,
} from "../../../generated/prisma";
import { z } from "zod";

const createApplicationZodSchema = z.object({
  companyId: z.string().optional(),
  companyNameSnapshot: z.string("Company name is required"),
  position: z.string("Position is required"),
  jobLink: z.string().url().optional(),
  jobLocation: z.string().optional(),
  jobNature: z.nativeEnum(JobNature).optional(),
  workMode: z.nativeEnum(WorkMode).optional(),
  experienceLevel: z.nativeEnum(ExperienceLevel).optional(),
  status: z.nativeEnum(ApplicationStatus).optional(),
  priority: z.nativeEnum(Priority).optional(),
  source: z.nativeEnum(ApplicationSource).optional(),
  appliedDate: z.string().datetime().optional(),
  deadline: z.string().datetime().optional(),
  followUpDate: z.string().datetime().optional(),
  salaryRangeMin: z.number().int().positive().optional(),
  salaryRangeMax: z.number().int().positive().optional(),
  currency: z.string().optional(),
  offerAmount: z.number().int().positive().optional(),
  techStack: z.array(z.string()).optional(),
  rejectionReason: z.string().optional(),
  hasTakeHome: z.boolean().optional(),
  takeHomeNotes: z.string().optional(),
  followUpCount: z.number().int().min(0).optional(),
  resumeDriveLink: z.string().optional(),
  coverLetterLink: z.string().optional(),
  comments: z.string().optional(),
  notes: z.string().optional(),
  isReferral: z.boolean().optional(),
  referredBy: z.string().optional(),
  tagIds: z.array(z.string()).optional(),
});

const updateApplicationZodSchema = z.object({
  companyId: z.string().optional(),
  companyNameSnapshot: z.string().optional(),
  position: z.string().optional(),
  jobLink: z.string().url().optional(),
  jobLocation: z.string().optional(),
  jobNature: z.nativeEnum(JobNature).optional(),
  workMode: z.nativeEnum(WorkMode).optional(),
  experienceLevel: z.nativeEnum(ExperienceLevel).optional(),
  status: z.nativeEnum(ApplicationStatus).optional(),
  priority: z.nativeEnum(Priority).optional(),
  source: z.nativeEnum(ApplicationSource).optional(),
  appliedDate: z.string().datetime().optional(),
  deadline: z.string().datetime().optional(),
  followUpDate: z.string().datetime().optional(),
  salaryRangeMin: z.number().int().positive().optional(),
  salaryRangeMax: z.number().int().positive().optional(),
  currency: z.string().optional(),
  offerAmount: z.number().int().positive().optional(),
  techStack: z.array(z.string()).optional(),
  rejectionReason: z.string().optional(),
  hasTakeHome: z.boolean().optional(),
  takeHomeNotes: z.string().optional(),
  followUpCount: z.number().int().min(0).optional(),
  resumeDriveLink: z.string().optional(),
  coverLetterLink: z.string().optional(),
  comments: z.string().optional(),
  notes: z.string().optional(),
  isReferral: z.boolean().optional(),
  referredBy: z.string().optional(),
  tagIds: z.array(z.string()).optional(),
});

export const ApplicationValidation = {
  createApplicationZodSchema,
  updateApplicationZodSchema,
};
